global:
  scrape_interval: 10s

# remote_write:
#   - url: http://host.docker.internal:9090/api/v1/push

scrape_configs:
  - job_name: 'server-singleprocess'
    static_configs:
      - targets: ['server-singleprocess:5000']

  - job_name: 'server-multiprocess'
    static_configs:
      - targets: ['server-multiprocess:5001']
