global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pytheus-singleprocess'
    static_configs:
      - targets: ['pytheus-singleprocess:5000']

  - job_name: 'pytheus-multiprocess'
    static_configs:
      - targets: ['pytheus-multiprocess:5001']

  - job_name: 'old-singleprocess'
    static_configs:
      - targets: ['old-singleprocess:5002']

  - job_name: 'old-multiprocess'
    static_configs:
      - targets: ['old-multiprocess:5003']
