global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pytheus-singleprocess'
    static_configs:
      - targets: ['pytheus-singleprocess:5000']

  - job_name: 'pytheus-multiprocess'
    static_configs:
      - targets: ['pytheus-multiprocess:5001']
